//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandrill_Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mandrill_Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandrill.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart object..
        /// </summary>
        public static string Chart_ChartDesc {
            get {
                return ResourceManager.GetString("Chart_ChartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Data object..
        /// </summary>
        public static string Chart_DataDesc {
            get {
                return ResourceManager.GetString("Chart_DataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Style object..
        /// </summary>
        public static string Chart_StyleDesc {
            get {
                return ResourceManager.GetString("Chart_StyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_AreaChart_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_AreaChart_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_AreaChart_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_AreaChart_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_AreaChart_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_AreaChart_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_AreaChart_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_AreaChart_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_BarChart_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_BarChart_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_BarChart_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_BarChart_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_BarChart_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_BarChart_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_BarChart_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_BarChart_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_DonutChart_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_DonutChart_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_DonutChart_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_DonutChart_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_DonutChart_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_DonutChart_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_DonutChart_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_DonutChart_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_GroupedBarChart_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_GroupedBarChart_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_GroupedBarChart_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_GroupedBarChart_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_GroupedBarChart_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_GroupedBarChart_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_GroupedBarChart_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_GroupedBarChart_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_HorizontalBarChart_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_HorizontalBarChart_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_HorizontalBarChart_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_HorizontalBarChart_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_HorizontalBarChart_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_HorizontalBarChart_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_HorizontalBarChart_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_HorizontalBarChart_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_LineChart_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_LineChart_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_LineChart_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_LineChart_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_LineChart_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_LineChart_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_LineChart_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_LineChart_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_MiscNodes_Address {
            get {
                object obj = ResourceManager.GetObject("Charts_MiscNodes_Address", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_MiscNodes_Domain {
            get {
                object obj = ResourceManager.GetObject("Charts_MiscNodes_Domain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_MiscNodes_Margins {
            get {
                object obj = ResourceManager.GetObject("Charts_MiscNodes_Margins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_NormalizedStackedBarChart_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_NormalizedStackedBarChart_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_NormalizedStackedBarChart_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_NormalizedStackedBarChart_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_NormalizedStackedBarChart_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_NormalizedStackedBarChart_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_NormalizedStackedBarChart_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_NormalizedStackedBarChart_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ParallelCoordinates_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_ParallelCoordinates_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ParallelCoordinates_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_ParallelCoordinates_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ParallelCoordinates_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_ParallelCoordinates_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ParallelCoordinates_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_ParallelCoordinates_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_PieChart_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_PieChart_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_PieChart_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_PieChart_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_PieChart_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_PieChart_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_PieChart_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_PieChart_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ScatterPlot_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_ScatterPlot_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ScatterPlot_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_ScatterPlot_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ScatterPlot_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_ScatterPlot_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ScatterPlot_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_ScatterPlot_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ScatterPlotMatrix_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_ScatterPlotMatrix_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ScatterPlotMatrix_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_ScatterPlotMatrix_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ScatterPlotMatrix_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_ScatterPlotMatrix_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_ScatterPlotMatrix_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_ScatterPlotMatrix_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_StackedBarChart_Chart {
            get {
                object obj = ResourceManager.GetObject("Charts_StackedBarChart_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_StackedBarChart_Data {
            get {
                object obj = ResourceManager.GetObject("Charts_StackedBarChart_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_StackedBarChart_DataFromCSV {
            get {
                object obj = ResourceManager.GetObject("Charts_StackedBarChart_DataFromCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Charts_StackedBarChart_Style {
            get {
                object obj = ResourceManager.GetObject("Charts_StackedBarChart_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain definiting upper and lower boundary of a chart Y-Axis..
        /// </summary>
        public static string Data_Domain {
            get {
                return ResourceManager.GetString("Data_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path to a CSV file..
        /// </summary>
        public static string Data_FilePathDesc {
            get {
                return ResourceManager.GetString("Data_FilePathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Header values..
        /// </summary>
        public static string Data_HeadersDesc {
            get {
                return ResourceManager.GetString("Data_HeadersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property of each value..
        /// </summary>
        public static string Data_NamesDesc {
            get {
                return ResourceManager.GetString("Data_NamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical value to plot..
        /// </summary>
        public static string Data_ValuesDesc {
            get {
                return ResourceManager.GetString("Data_ValuesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Tree where each branch represents a group of values/row..
        /// </summary>
        public static string Data_ValuesTreeDesc {
            get {
                return ResourceManager.GetString("Data_ValuesTreeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Image_Create {
            get {
                object obj = ResourceManager.GetObject("Image_Image_Create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Image_Style {
            get {
                object obj = ResourceManager.GetObject("Image_Image_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Image object..
        /// </summary>
        public static string Image_ImageDesc {
            get {
                return ResourceManager.GetString("Image_ImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style for an Image object..
        /// </summary>
        public static string Image_StyleDesc {
            get {
                return ResourceManager.GetString("Image_StyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Legends_Legend_Create {
            get {
                object obj = ResourceManager.GetObject("Legends_Legend_Create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Legends_Legend_Data {
            get {
                object obj = ResourceManager.GetObject("Legends_Legend_Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Legends_Legend_Style {
            get {
                object obj = ResourceManager.GetObject("Legends_Legend_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mandrill_ChromeWindow_MandrillChromeWindowNodeModel {
            get {
                object obj = ResourceManager.GetObject("Mandrill_ChromeWindow_MandrillChromeWindowNodeModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mandrill_ChromeWindow_MandrillReportNode_MandrillReportNode {
            get {
                object obj = ResourceManager.GetObject("Mandrill_ChromeWindow_MandrillReportNode_MandrillReportNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mandrill_Print_MandrillPrintNodeModel {
            get {
                object obj = ResourceManager.GetObject("Mandrill_Print_MandrillPrintNodeModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mandrill_UI_pdf_FitModeUI_pdf_FitModeUI {
            get {
                object obj = ResourceManager.GetObject("Mandrill_UI_pdf_FitModeUI_pdf_FitModeUI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mandrill_UI_pdf_OrientationUI_pdf_OrientationUI {
            get {
                object obj = ResourceManager.GetObject("Mandrill_UI_pdf_OrientationUI_pdf_OrientationUI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mandrill_UI_pdf_SizeUI_pdf_SizeUI {
            get {
                object obj = ResourceManager.GetObject("Mandrill_UI_pdf_SizeUI_pdf_SizeUI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mandrill_UI_tn_FontStyle_tn_FontStyle {
            get {
                object obj = ResourceManager.GetObject("Mandrill_UI_tn_FontStyle_tn_FontStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mandrill_UI_tn_FontTransform_tn_FontTransform {
            get {
                object obj = ResourceManager.GetObject("Mandrill_UI_tn_FontTransform_tn_FontTransform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mandrill_UI_tn_FontWeight_tn_FontWeight {
            get {
                object obj = ResourceManager.GetObject("Mandrill_UI_tn_FontWeight_tn_FontWeight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mandrillLogo {
            get {
                object obj = ResourceManager.GetObject("mandrillLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the Chart in X grid..
        /// </summary>
        public static string Misc_AddressColumnDesc {
            get {
                return ResourceManager.GetString("Misc_AddressColumnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the Chart in Y grid..
        /// </summary>
        public static string Misc_AddressRowDesc {
            get {
                return ResourceManager.GetString("Misc_AddressRowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom margin in pixels.
        /// </summary>
        public static string Misc_BottomMarginDesc {
            get {
                return ResourceManager.GetString("Misc_BottomMarginDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top boundary of the domain..
        /// </summary>
        public static string Misc_DomainEndDesc {
            get {
                return ResourceManager.GetString("Misc_DomainEndDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom boundary of the domain..
        /// </summary>
        public static string Misc_DomainStartDesc {
            get {
                return ResourceManager.GetString("Misc_DomainStartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left margin in pixels..
        /// </summary>
        public static string Misc_LeftMarginDesc {
            get {
                return ResourceManager.GetString("Misc_LeftMarginDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right margin in pixels..
        /// </summary>
        public static string Misc_RightMarginDesc {
            get {
                return ResourceManager.GetString("Misc_RightMarginDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top margin in pixels..
        /// </summary>
        public static string Misc_TopMarginDesc {
            get {
                return ResourceManager.GetString("Misc_TopMarginDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF object..
        /// </summary>
        public static string PDF_PDFDesc {
            get {
                return ResourceManager.GetString("PDF_PDFDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Style object..
        /// </summary>
        public static string PDF_StyleDesc {
            get {
                return ResourceManager.GetString("PDF_StyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Report_Pdf_Style {
            get {
                object obj = ResourceManager.GetObject("Report_Pdf_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report object..
        /// </summary>
        public static string Report_ReportDesc {
            get {
                return ResourceManager.GetString("Report_ReportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this boolean to true to launch Mandrill window..
        /// </summary>
        public static string Report_ShowWindowDesc {
            get {
                return ResourceManager.GetString("Report_ShowWindowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid coordinates for chart placement..
        /// </summary>
        public static string Style_AddressDesc {
            get {
                return ResourceManager.GetString("Style_AddressDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill color for Area..
        /// </summary>
        public static string Style_AreaColorDesc {
            get {
                return ResourceManager.GetString("Style_AreaColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill color for Bars..
        /// </summary>
        public static string Style_BarColorDesc {
            get {
                return ResourceManager.GetString("Style_BarColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Colors..
        /// </summary>
        public static string Style_ColorsDesc {
            get {
                return ResourceManager.GetString("Style_ColorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value between 0-100 where 0 is best image quality while 100 ensures highest compression and lowest image quality..
        /// </summary>
        public static string Style_CompressionDesc {
            get {
                return ResourceManager.GetString("Style_CompressionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the Font..
        /// </summary>
        public static string Style_FontColorDesc {
            get {
                return ResourceManager.GetString("Style_FontColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the Font. Default is 20px..
        /// </summary>
        public static string Style_FontSizeDesc {
            get {
                return ResourceManager.GetString("Style_FontSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style of the Font. Default is &quot;normal&quot;..
        /// </summary>
        public static string Style_FontStyleDesc {
            get {
                return ResourceManager.GetString("Style_FontStyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform of the Font. Default is &quot;normal&quot;..
        /// </summary>
        public static string Style_FontTransformDesc {
            get {
                return ResourceManager.GetString("Style_FontTransformDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight of the Font. Default is &quot;normal&quot;..
        /// </summary>
        public static string Style_FontWeightDesc {
            get {
                return ResourceManager.GetString("Style_FontWeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height of the chart in pixels..
        /// </summary>
        public static string Style_HeightDesc {
            get {
                return ResourceManager.GetString("Style_HeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill color when hoverd over..
        /// </summary>
        public static string Style_HoverColorDesc {
            get {
                return ResourceManager.GetString("Style_HoverColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip message that will appear when you hover over image..
        /// </summary>
        public static string Style_ImageTooltipDesc {
            get {
                return ResourceManager.GetString("Style_ImageTooltipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean value that controls if labels are displayed..
        /// </summary>
        public static string Style_LabelsDesc {
            get {
                return ResourceManager.GetString("Style_LabelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the Line..
        /// </summary>
        public static string Style_LineColorDesc {
            get {
                return ResourceManager.GetString("Style_LineColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin value in points where 1 point is 1/72 inches..
        /// </summary>
        public static string Style_MarginDesc {
            get {
                return ResourceManager.GetString("Style_MarginDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins around the chart (space for labels, axis etc.).
        /// </summary>
        public static string Style_MarginsDesc {
            get {
                return ResourceManager.GetString("Style_MarginsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines if Report will be resized (width) to automatically fit onto specified page size..
        /// </summary>
        public static string Style_PdfHorizontalFitDesc {
            get {
                return ResourceManager.GetString("Style_PdfHorizontalFitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation for the generated PDF document. Example: Landscape..
        /// </summary>
        public static string Style_PdfOrientationDesc {
            get {
                return ResourceManager.GetString("Style_PdfOrientationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the generated PDF Document. Example: Letter, 11x17 etc..
        /// </summary>
        public static string Style_PdfSizeDesc {
            get {
                return ResourceManager.GetString("Style_PdfSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines if Report will be resized (height) to automatically fit onto specified page size..
        /// </summary>
        public static string Style_PdfVerticalFitDesc {
            get {
                return ResourceManager.GetString("Style_PdfVerticalFitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximate number of tick marks displayed for X-Axis.
        /// </summary>
        public static string Style_TickMarksXDesc {
            get {
                return ResourceManager.GetString("Style_TickMarksXDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text appearing at center of the chart..
        /// </summary>
        public static string Style_TotalLabelDesc {
            get {
                return ResourceManager.GetString("Style_TotalLabelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of the chart in pixels..
        /// </summary>
        public static string Style_WidthDesc {
            get {
                return ResourceManager.GetString("Style_WidthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies if labels along X-Axis are rotated..
        /// </summary>
        public static string Style_XTextRotationDesc {
            get {
                return ResourceManager.GetString("Style_XTextRotationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text displayed in the top/left corner of chart..
        /// </summary>
        public static string Style_YAxisLabelDesc {
            get {
                return ResourceManager.GetString("Style_YAxisLabelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multivariate.
        /// </summary>
        public static string SubCategory_Multivariate {
            get {
                return ResourceManager.GetString("SubCategory_Multivariate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter Plots.
        /// </summary>
        public static string SubCategory_ScatterPlot {
            get {
                return ResourceManager.GetString("SubCategory_ScatterPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string SubCategory_Text {
            get {
                return ResourceManager.GetString("SubCategory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaCharts.
        /// </summary>
        public static string SubCategoryAreaChart {
            get {
                return ResourceManager.GetString("SubCategoryAreaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCharts.
        /// </summary>
        public static string SubCategoryBarChart {
            get {
                return ResourceManager.GetString("SubCategoryBarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DonutCharts.
        /// </summary>
        public static string SubCategoryDonutChartDesc {
            get {
                return ResourceManager.GetString("SubCategoryDonutChartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string SubCategoryImage {
            get {
                return ResourceManager.GetString("SubCategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineCharts.
        /// </summary>
        public static string SubCategoryLineChart {
            get {
                return ResourceManager.GetString("SubCategoryLineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string SubCategoryMisc {
            get {
                return ResourceManager.GetString("SubCategoryMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string SubCategoryPDF {
            get {
                return ResourceManager.GetString("SubCategoryPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string SubCategoryReport {
            get {
                return ResourceManager.GetString("SubCategoryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text style object..
        /// </summary>
        public static string Text_StyleDesc {
            get {
                return ResourceManager.GetString("Text_StyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Text_Text_Create {
            get {
                object obj = ResourceManager.GetObject("Text_Text_Create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Text_Text_Style {
            get {
                object obj = ResourceManager.GetObject("Text_Text_Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test object..
        /// </summary>
        public static string Text_TextDesc {
            get {
                return ResourceManager.GetString("Text_TextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual text that will be displayed..
        /// </summary>
        public static string Text_TextValueDesc {
            get {
                return ResourceManager.GetString("Text_TextValueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of more inputs are missing appropriate data..
        /// </summary>
        public static string Warning_MissingInput {
            get {
                return ResourceManager.GetString("Warning_MissingInput", resourceCulture);
            }
        }
    }
}
